# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsi', models.CharField(max_length=32)),
                ('field', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('imsi', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('signal_q', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reg_status', models.CharField(blank=True, max_length=32, null=True)),
                ('cipher_ind', models.NullBooleanField()),
                ('kc', models.CharField(blank=True, max_length=20, null=True)),
                ('kc_gprs', models.CharField(blank=True, max_length=20, null=True)),
                ('cipher_key', models.CharField(blank=True, max_length=32, null=True)),
                ('integrity_key', models.CharField(blank=True, max_length=32, null=True)),
                ('tmsi', models.CharField(blank=True, max_length=20, null=True)),
                ('tmsi_time', models.PositiveIntegerField(blank=True, null=True)),
                ('lai', models.CharField(blank=True, max_length=12, null=True)),
                ('ptmsi', models.CharField(blank=True, max_length=8, null=True)),
                ('ptmsi_sign', models.CharField(blank=True, max_length=6, null=True)),
                ('rai', models.CharField(blank=True, max_length=12, null=True)),
                ('threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_vendor', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_model', models.CharField(blank=True, max_length=10, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=10, null=True)),
                ('imei', models.CharField(blank=True, max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivePhone',
            fields=[
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eos.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='LogDashboard',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eos.log',),
        ),
    ]
